import styles from '../styles/common.module.scss'
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer'
import Banner from "../components/Banner/Banner"
import Head from 'next/head'

let csstyle={
    backgroundColor: "#E95546",
    color:"white",
}



let img={
    width: "200px",
    height: "40px"
}

export default function Contentstack({data}){
    let {CS}=data
    return (
        
        <div className={styles.container}>
            <Head>
                <title>Contentstack</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/cs.png" />
            </Head>
            <Navbar data={CS} style={csstyle} imagestyle={img}/>
            <Banner data={CS}  />
            <Footer data={CS["footerData"]} style={csstyle} />
        </div>

    )
}

export async function getStaticProps() {
    // Get external data from the file system, API, DB, etc.
    let response = await fetch("https://pawan43563.github.io/json-files/company-data.json")
    let data=await response.json()
    // The value of the `props` key will be
    //  passed to the `Home` component
    return {
      props: {
          data,
      }
    }
}