import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import Card from '../components/Card/Card'
import Footer from '../components/Footer/Footer'
import Navbar from '../components/Navbar/Navbar'

let style={
  width:"100px",
  height:"60px"
}

export default function Home({data}) {
  let {CS,SB,RE}=data
  return (
    <div className={styles.container}>
      <Head>
        <title>Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar data={data["Home"]} imagestyle={style}/>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>
        <p className={styles.description}>
          To our all in one company's website.
        </p>
        <div className={styles.grid}>
          <Card data={CS} />
          <Card data={RE} />
          <Card data={SB} />
        </div>
          
      </main>
     
      <Footer data={data["Home"]} imagestyle={style}/>
    </div>
  )
}


export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
  let response = await fetch("https://pawan43563.github.io/json-files/company-data.json")
  let data=await response.json()
  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: {
        data,
    }
  }
}